dataset:
  repo_id: xlerobot_home_so101_single_arm
  root: data/lerobot/xlerobot_home_so101_single_arm

policy:
  type: act
  chunk_size: 5
  n_action_steps: 5
  device: cuda

output_dir: models/xlerobot-home-so101-act
job_name: xlerobot_home_so101_act
resume: false
seed: 42
batch_size: 16
num_workers: 8
steps: 20_000
eval_freq: -1
log_freq: 50
save_checkpoint: true
save_freq: 10_000
use_policy_training_preset: true

wandb:
  enable: false
  project: xlerobot_home_so101_act
  entity: ""
  disable_artifact: true
