[mypy]
python_version = 3.12
show_error_codes = true
warn_return_any = true
warn_unused_configs = true
disallow_untyped_calls = false
check_untyped_defs = true
exclude_gitignore = true
ignore_missing_imports = true
exclude = ^src/hey_robot/(foundation/contract/v1/model_service_pb2(_grpc)?|robocasa_backend/rpc/v1/robocasa_runtime_pb2(_grpc)?)\.py$
