# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""

import grpc
import warnings

from . import robocasa_runtime_pb2 as robocasa__runtime__pb2

GRPC_GENERATED_VERSION = "1.73.1"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(
        GRPC_VERSION, GRPC_GENERATED_VERSION
    )
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + f" but the generated code in robocasa_runtime_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class RoboCasaRuntimeStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetHealth = channel.unary_unary(
            "/hey_robot.robocasa_runtime.v1.RoboCasaRuntime/GetHealth",
            request_serializer=robocasa__runtime__pb2.HealthRequest.SerializeToString,
            response_deserializer=robocasa__runtime__pb2.HealthResponse.FromString,
            _registered_method=True,
        )
        self.BeginTrial = channel.unary_unary(
            "/hey_robot.robocasa_runtime.v1.RoboCasaRuntime/BeginTrial",
            request_serializer=robocasa__runtime__pb2.BeginTrialRequest.SerializeToString,
            response_deserializer=robocasa__runtime__pb2.ObservationResponse.FromString,
            _registered_method=True,
        )
        self.Observe = channel.unary_unary(
            "/hey_robot.robocasa_runtime.v1.RoboCasaRuntime/Observe",
            request_serializer=robocasa__runtime__pb2.EmptyRequest.SerializeToString,
            response_deserializer=robocasa__runtime__pb2.ObservationResponse.FromString,
            _registered_method=True,
        )
        self.Step = channel.unary_unary(
            "/hey_robot.robocasa_runtime.v1.RoboCasaRuntime/Step",
            request_serializer=robocasa__runtime__pb2.StepRequest.SerializeToString,
            response_deserializer=robocasa__runtime__pb2.StepResponse.FromString,
            _registered_method=True,
        )
        self.StepNative = channel.unary_unary(
            "/hey_robot.robocasa_runtime.v1.RoboCasaRuntime/StepNative",
            request_serializer=robocasa__runtime__pb2.NativeStepRequest.SerializeToString,
            response_deserializer=robocasa__runtime__pb2.NativeStepResponse.FromString,
            _registered_method=True,
        )
        self.LocalizePixels = channel.unary_unary(
            "/hey_robot.robocasa_runtime.v1.RoboCasaRuntime/LocalizePixels",
            request_serializer=robocasa__runtime__pb2.LocalizePixelsRequest.SerializeToString,
            response_deserializer=robocasa__runtime__pb2.LocalizePixelsResponse.FromString,
            _registered_method=True,
        )
        self.ReadTruth = channel.unary_unary(
            "/hey_robot.robocasa_runtime.v1.RoboCasaRuntime/ReadTruth",
            request_serializer=robocasa__runtime__pb2.EmptyRequest.SerializeToString,
            response_deserializer=robocasa__runtime__pb2.TruthResponse.FromString,
            _registered_method=True,
        )
        self.EndTrial = channel.unary_unary(
            "/hey_robot.robocasa_runtime.v1.RoboCasaRuntime/EndTrial",
            request_serializer=robocasa__runtime__pb2.EndTrialRequest.SerializeToString,
            response_deserializer=robocasa__runtime__pb2.EndTrialResponse.FromString,
            _registered_method=True,
        )


class RoboCasaRuntimeServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetHealth(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def BeginTrial(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def Observe(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def Step(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def StepNative(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def LocalizePixels(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def ReadTruth(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def EndTrial(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_RoboCasaRuntimeServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "GetHealth": grpc.unary_unary_rpc_method_handler(
            servicer.GetHealth,
            request_deserializer=robocasa__runtime__pb2.HealthRequest.FromString,
            response_serializer=robocasa__runtime__pb2.HealthResponse.SerializeToString,
        ),
        "BeginTrial": grpc.unary_unary_rpc_method_handler(
            servicer.BeginTrial,
            request_deserializer=robocasa__runtime__pb2.BeginTrialRequest.FromString,
            response_serializer=robocasa__runtime__pb2.ObservationResponse.SerializeToString,
        ),
        "Observe": grpc.unary_unary_rpc_method_handler(
            servicer.Observe,
            request_deserializer=robocasa__runtime__pb2.EmptyRequest.FromString,
            response_serializer=robocasa__runtime__pb2.ObservationResponse.SerializeToString,
        ),
        "Step": grpc.unary_unary_rpc_method_handler(
            servicer.Step,
            request_deserializer=robocasa__runtime__pb2.StepRequest.FromString,
            response_serializer=robocasa__runtime__pb2.StepResponse.SerializeToString,
        ),
        "StepNative": grpc.unary_unary_rpc_method_handler(
            servicer.StepNative,
            request_deserializer=robocasa__runtime__pb2.NativeStepRequest.FromString,
            response_serializer=robocasa__runtime__pb2.NativeStepResponse.SerializeToString,
        ),
        "LocalizePixels": grpc.unary_unary_rpc_method_handler(
            servicer.LocalizePixels,
            request_deserializer=robocasa__runtime__pb2.LocalizePixelsRequest.FromString,
            response_serializer=robocasa__runtime__pb2.LocalizePixelsResponse.SerializeToString,
        ),
        "ReadTruth": grpc.unary_unary_rpc_method_handler(
            servicer.ReadTruth,
            request_deserializer=robocasa__runtime__pb2.EmptyRequest.FromString,
            response_serializer=robocasa__runtime__pb2.TruthResponse.SerializeToString,
        ),
        "EndTrial": grpc.unary_unary_rpc_method_handler(
            servicer.EndTrial,
            request_deserializer=robocasa__runtime__pb2.EndTrialRequest.FromString,
            response_serializer=robocasa__runtime__pb2.EndTrialResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "hey_robot.robocasa_runtime.v1.RoboCasaRuntime", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers(
        "hey_robot.robocasa_runtime.v1.RoboCasaRuntime", rpc_method_handlers
    )


# This class is part of an EXPERIMENTAL API.
class RoboCasaRuntime(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetHealth(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/hey_robot.robocasa_runtime.v1.RoboCasaRuntime/GetHealth",
            robocasa__runtime__pb2.HealthRequest.SerializeToString,
            robocasa__runtime__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def BeginTrial(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/hey_robot.robocasa_runtime.v1.RoboCasaRuntime/BeginTrial",
            robocasa__runtime__pb2.BeginTrialRequest.SerializeToString,
            robocasa__runtime__pb2.ObservationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def Observe(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/hey_robot.robocasa_runtime.v1.RoboCasaRuntime/Observe",
            robocasa__runtime__pb2.EmptyRequest.SerializeToString,
            robocasa__runtime__pb2.ObservationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def Step(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/hey_robot.robocasa_runtime.v1.RoboCasaRuntime/Step",
            robocasa__runtime__pb2.StepRequest.SerializeToString,
            robocasa__runtime__pb2.StepResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def StepNative(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/hey_robot.robocasa_runtime.v1.RoboCasaRuntime/StepNative",
            robocasa__runtime__pb2.NativeStepRequest.SerializeToString,
            robocasa__runtime__pb2.NativeStepResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def LocalizePixels(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/hey_robot.robocasa_runtime.v1.RoboCasaRuntime/LocalizePixels",
            robocasa__runtime__pb2.LocalizePixelsRequest.SerializeToString,
            robocasa__runtime__pb2.LocalizePixelsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def ReadTruth(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/hey_robot.robocasa_runtime.v1.RoboCasaRuntime/ReadTruth",
            robocasa__runtime__pb2.EmptyRequest.SerializeToString,
            robocasa__runtime__pb2.TruthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def EndTrial(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/hey_robot.robocasa_runtime.v1.RoboCasaRuntime/EndTrial",
            robocasa__runtime__pb2.EndTrialRequest.SerializeToString,
            robocasa__runtime__pb2.EndTrialResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
