# ruff: noqa
# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""

import grpc
import warnings

from hey_robot.foundation.contract.v1 import (
    model_service_pb2 as hey__robot_dot_model__service_dot_v1_dot_model__service__pb2,
)

GRPC_GENERATED_VERSION = "1.73.1"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(
        GRPC_VERSION, GRPC_GENERATED_VERSION
    )
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + f" but the generated code in hey_robot/foundation/contract/v1/model_service_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class ModelServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetHealth = channel.unary_unary(
            "/hey_robot.model_service.v1.ModelService/GetHealth",
            request_serializer=hey__robot_dot_model__service_dot_v1_dot_model__service__pb2.GetHealthRequest.SerializeToString,
            response_deserializer=hey__robot_dot_model__service_dot_v1_dot_model__service__pb2.GetHealthResponse.FromString,
            _registered_method=True,
        )
        self.ExecuteSkill = channel.unary_unary(
            "/hey_robot.model_service.v1.ModelService/ExecuteSkill",
            request_serializer=hey__robot_dot_model__service_dot_v1_dot_model__service__pb2.ExecuteSkillRequest.SerializeToString,
            response_deserializer=hey__robot_dot_model__service_dot_v1_dot_model__service__pb2.ExecuteSkillResponse.FromString,
            _registered_method=True,
        )
        self.CancelSkill = channel.unary_unary(
            "/hey_robot.model_service.v1.ModelService/CancelSkill",
            request_serializer=hey__robot_dot_model__service_dot_v1_dot_model__service__pb2.CancelSkillRequest.SerializeToString,
            response_deserializer=hey__robot_dot_model__service_dot_v1_dot_model__service__pb2.CancelSkillResponse.FromString,
            _registered_method=True,
        )


class ModelServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetHealth(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def ExecuteSkill(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def CancelSkill(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_ModelServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "GetHealth": grpc.unary_unary_rpc_method_handler(
            servicer.GetHealth,
            request_deserializer=hey__robot_dot_model__service_dot_v1_dot_model__service__pb2.GetHealthRequest.FromString,
            response_serializer=hey__robot_dot_model__service_dot_v1_dot_model__service__pb2.GetHealthResponse.SerializeToString,
        ),
        "ExecuteSkill": grpc.unary_unary_rpc_method_handler(
            servicer.ExecuteSkill,
            request_deserializer=hey__robot_dot_model__service_dot_v1_dot_model__service__pb2.ExecuteSkillRequest.FromString,
            response_serializer=hey__robot_dot_model__service_dot_v1_dot_model__service__pb2.ExecuteSkillResponse.SerializeToString,
        ),
        "CancelSkill": grpc.unary_unary_rpc_method_handler(
            servicer.CancelSkill,
            request_deserializer=hey__robot_dot_model__service_dot_v1_dot_model__service__pb2.CancelSkillRequest.FromString,
            response_serializer=hey__robot_dot_model__service_dot_v1_dot_model__service__pb2.CancelSkillResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "hey_robot.model_service.v1.ModelService", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers(
        "hey_robot.model_service.v1.ModelService", rpc_method_handlers
    )


# This class is part of an EXPERIMENTAL API.
class ModelService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetHealth(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/hey_robot.model_service.v1.ModelService/GetHealth",
            hey__robot_dot_model__service_dot_v1_dot_model__service__pb2.GetHealthRequest.SerializeToString,
            hey__robot_dot_model__service_dot_v1_dot_model__service__pb2.GetHealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def ExecuteSkill(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/hey_robot.model_service.v1.ModelService/ExecuteSkill",
            hey__robot_dot_model__service_dot_v1_dot_model__service__pb2.ExecuteSkillRequest.SerializeToString,
            hey__robot_dot_model__service_dot_v1_dot_model__service__pb2.ExecuteSkillResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def CancelSkill(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/hey_robot.model_service.v1.ModelService/CancelSkill",
            hey__robot_dot_model__service_dot_v1_dot_model__service__pb2.CancelSkillRequest.SerializeToString,
            hey__robot_dot_model__service_dot_v1_dot_model__service__pb2.CancelSkillResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
