# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""

import grpc
import warnings

from hey_robot.robocasa_runtime.v1 import (
    robocasa_runtime_pb2 as hey__robot_dot_robocasa__runtime_dot_v1_dot_robocasa__runtime__pb2,
)

GRPC_GENERATED_VERSION = "1.73.1"
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower

    _version_not_supported = first_version_is_lower(
        GRPC_VERSION, GRPC_GENERATED_VERSION
    )
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f"The grpc package installed is at version {GRPC_VERSION},"
        + f" but the generated code in hey_robot/robocasa_runtime/v1/robocasa_runtime_pb2_grpc.py depends on"
        + f" grpcio>={GRPC_GENERATED_VERSION}."
        + f" Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}"
        + f" or downgrade your generated code using grpcio-tools<={GRPC_VERSION}."
    )


class RoboCasaRuntimeStub(object):
    """The high-frequency simulator boundary. This is deliberately separate from
    ModelService: a policy rollout owns an episode, while RobotDriver performs
    causal Observe/Step calls against one episode at a time.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetHealth = channel.unary_unary(
            "/hey_robot.robocasa_runtime.v1.RoboCasaRuntime/GetHealth",
            request_serializer=hey__robot_dot_robocasa__runtime_dot_v1_dot_robocasa__runtime__pb2.HealthRequest.SerializeToString,
            response_deserializer=hey__robot_dot_robocasa__runtime_dot_v1_dot_robocasa__runtime__pb2.HealthResponse.FromString,
            _registered_method=True,
        )
        self.CreateEpisode = channel.unary_unary(
            "/hey_robot.robocasa_runtime.v1.RoboCasaRuntime/CreateEpisode",
            request_serializer=hey__robot_dot_robocasa__runtime_dot_v1_dot_robocasa__runtime__pb2.CreateEpisodeRequest.SerializeToString,
            response_deserializer=hey__robot_dot_robocasa__runtime_dot_v1_dot_robocasa__runtime__pb2.EpisodeResponse.FromString,
            _registered_method=True,
        )
        self.Observe = channel.unary_unary(
            "/hey_robot.robocasa_runtime.v1.RoboCasaRuntime/Observe",
            request_serializer=hey__robot_dot_robocasa__runtime_dot_v1_dot_robocasa__runtime__pb2.EpisodeRequest.SerializeToString,
            response_deserializer=hey__robot_dot_robocasa__runtime_dot_v1_dot_robocasa__runtime__pb2.ObservationResponse.FromString,
            _registered_method=True,
        )
        self.Step = channel.unary_unary(
            "/hey_robot.robocasa_runtime.v1.RoboCasaRuntime/Step",
            request_serializer=hey__robot_dot_robocasa__runtime_dot_v1_dot_robocasa__runtime__pb2.StepRequest.SerializeToString,
            response_deserializer=hey__robot_dot_robocasa__runtime_dot_v1_dot_robocasa__runtime__pb2.StepResponse.FromString,
            _registered_method=True,
        )
        self.Reset = channel.unary_unary(
            "/hey_robot.robocasa_runtime.v1.RoboCasaRuntime/Reset",
            request_serializer=hey__robot_dot_robocasa__runtime_dot_v1_dot_robocasa__runtime__pb2.EpisodeRequest.SerializeToString,
            response_deserializer=hey__robot_dot_robocasa__runtime_dot_v1_dot_robocasa__runtime__pb2.ObservationResponse.FromString,
            _registered_method=True,
        )
        self.CloseEpisode = channel.unary_unary(
            "/hey_robot.robocasa_runtime.v1.RoboCasaRuntime/CloseEpisode",
            request_serializer=hey__robot_dot_robocasa__runtime_dot_v1_dot_robocasa__runtime__pb2.EpisodeRequest.SerializeToString,
            response_deserializer=hey__robot_dot_robocasa__runtime_dot_v1_dot_robocasa__runtime__pb2.CloseEpisodeResponse.FromString,
            _registered_method=True,
        )


class RoboCasaRuntimeServicer(object):
    """The high-frequency simulator boundary. This is deliberately separate from
    ModelService: a policy rollout owns an episode, while RobotDriver performs
    causal Observe/Step calls against one episode at a time.
    """

    def GetHealth(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def CreateEpisode(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def Observe(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def Step(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def Reset(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")

    def CloseEpisode(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details("Method not implemented!")
        raise NotImplementedError("Method not implemented!")


def add_RoboCasaRuntimeServicer_to_server(servicer, server):
    rpc_method_handlers = {
        "GetHealth": grpc.unary_unary_rpc_method_handler(
            servicer.GetHealth,
            request_deserializer=hey__robot_dot_robocasa__runtime_dot_v1_dot_robocasa__runtime__pb2.HealthRequest.FromString,
            response_serializer=hey__robot_dot_robocasa__runtime_dot_v1_dot_robocasa__runtime__pb2.HealthResponse.SerializeToString,
        ),
        "CreateEpisode": grpc.unary_unary_rpc_method_handler(
            servicer.CreateEpisode,
            request_deserializer=hey__robot_dot_robocasa__runtime_dot_v1_dot_robocasa__runtime__pb2.CreateEpisodeRequest.FromString,
            response_serializer=hey__robot_dot_robocasa__runtime_dot_v1_dot_robocasa__runtime__pb2.EpisodeResponse.SerializeToString,
        ),
        "Observe": grpc.unary_unary_rpc_method_handler(
            servicer.Observe,
            request_deserializer=hey__robot_dot_robocasa__runtime_dot_v1_dot_robocasa__runtime__pb2.EpisodeRequest.FromString,
            response_serializer=hey__robot_dot_robocasa__runtime_dot_v1_dot_robocasa__runtime__pb2.ObservationResponse.SerializeToString,
        ),
        "Step": grpc.unary_unary_rpc_method_handler(
            servicer.Step,
            request_deserializer=hey__robot_dot_robocasa__runtime_dot_v1_dot_robocasa__runtime__pb2.StepRequest.FromString,
            response_serializer=hey__robot_dot_robocasa__runtime_dot_v1_dot_robocasa__runtime__pb2.StepResponse.SerializeToString,
        ),
        "Reset": grpc.unary_unary_rpc_method_handler(
            servicer.Reset,
            request_deserializer=hey__robot_dot_robocasa__runtime_dot_v1_dot_robocasa__runtime__pb2.EpisodeRequest.FromString,
            response_serializer=hey__robot_dot_robocasa__runtime_dot_v1_dot_robocasa__runtime__pb2.ObservationResponse.SerializeToString,
        ),
        "CloseEpisode": grpc.unary_unary_rpc_method_handler(
            servicer.CloseEpisode,
            request_deserializer=hey__robot_dot_robocasa__runtime_dot_v1_dot_robocasa__runtime__pb2.EpisodeRequest.FromString,
            response_serializer=hey__robot_dot_robocasa__runtime_dot_v1_dot_robocasa__runtime__pb2.CloseEpisodeResponse.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        "hey_robot.robocasa_runtime.v1.RoboCasaRuntime", rpc_method_handlers
    )
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers(
        "hey_robot.robocasa_runtime.v1.RoboCasaRuntime", rpc_method_handlers
    )


# This class is part of an EXPERIMENTAL API.
class RoboCasaRuntime(object):
    """The high-frequency simulator boundary. This is deliberately separate from
    ModelService: a policy rollout owns an episode, while RobotDriver performs
    causal Observe/Step calls against one episode at a time.
    """

    @staticmethod
    def GetHealth(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/hey_robot.robocasa_runtime.v1.RoboCasaRuntime/GetHealth",
            hey__robot_dot_robocasa__runtime_dot_v1_dot_robocasa__runtime__pb2.HealthRequest.SerializeToString,
            hey__robot_dot_robocasa__runtime_dot_v1_dot_robocasa__runtime__pb2.HealthResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def CreateEpisode(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/hey_robot.robocasa_runtime.v1.RoboCasaRuntime/CreateEpisode",
            hey__robot_dot_robocasa__runtime_dot_v1_dot_robocasa__runtime__pb2.CreateEpisodeRequest.SerializeToString,
            hey__robot_dot_robocasa__runtime_dot_v1_dot_robocasa__runtime__pb2.EpisodeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def Observe(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/hey_robot.robocasa_runtime.v1.RoboCasaRuntime/Observe",
            hey__robot_dot_robocasa__runtime_dot_v1_dot_robocasa__runtime__pb2.EpisodeRequest.SerializeToString,
            hey__robot_dot_robocasa__runtime_dot_v1_dot_robocasa__runtime__pb2.ObservationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def Step(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/hey_robot.robocasa_runtime.v1.RoboCasaRuntime/Step",
            hey__robot_dot_robocasa__runtime_dot_v1_dot_robocasa__runtime__pb2.StepRequest.SerializeToString,
            hey__robot_dot_robocasa__runtime_dot_v1_dot_robocasa__runtime__pb2.StepResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def Reset(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/hey_robot.robocasa_runtime.v1.RoboCasaRuntime/Reset",
            hey__robot_dot_robocasa__runtime_dot_v1_dot_robocasa__runtime__pb2.EpisodeRequest.SerializeToString,
            hey__robot_dot_robocasa__runtime_dot_v1_dot_robocasa__runtime__pb2.ObservationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )

    @staticmethod
    def CloseEpisode(
        request,
        target,
        options=(),
        channel_credentials=None,
        call_credentials=None,
        insecure=False,
        compression=None,
        wait_for_ready=None,
        timeout=None,
        metadata=None,
    ):
        return grpc.experimental.unary_unary(
            request,
            target,
            "/hey_robot.robocasa_runtime.v1.RoboCasaRuntime/CloseEpisode",
            hey__robot_dot_robocasa__runtime_dot_v1_dot_robocasa__runtime__pb2.EpisodeRequest.SerializeToString,
            hey__robot_dot_robocasa__runtime_dot_v1_dot_robocasa__runtime__pb2.CloseEpisodeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True,
        )
